### ISSUE TITLE
PERF error thrown when validating XSD schema

### ISSUE THREAD

**Issue by lbauret** [mulesoft-labs/raml-xml-validation#1]
When validating complex XSD schemas that contain nested references, the library is throwing an exception with "PERF error" message.
```
Error: Unable to render embedded object: File (_PERF_) not found.
at Object.Module.printErr.Module.printErr (worker.js:389662)
at i (worker.js:389662)
at run (worker.js:389662)
at Object.xmllint.validateXML (worker.js:389788)
```

This behavior is inconsistent and is thrown occasionally even with the same XML and XSD inputs.

**Comment by postatum** [comment]
Resolved in version 0.1.0
